# ======================
# SOURCE: PostgreSQL
# ======================
debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.database.hostname=postgres
debezium.source.database.port=5432
debezium.source.database.user=app_user
debezium.source.database.password=app_password
debezium.source.database.dbname=app_db
debezium.source.database.server.name=pgserver
debezium.source.plugin.name=pgoutput
debezium.source.publication.name=debezium_pub
debezium.source.slot.name=debezium_slot

# ======================
# SINK: ClickHouse
# ======================
debezium.sink.type=jdbc
debezium.sink.jdbc.url=jdbc:clickhouse://clickhouse:9000/analytics
debezium.sink.jdbc.user=default
debezium.sink.jdbc.password=

# ======================
# FORMAT
# ======================
debezium.format.key=json
debezium.format.value=json
